
 export const COUNTRYCODES = [
	{value: null, viewValue: '', viewName: ''},
    {value: 'at', viewValue: 'AT', viewName: 'Austria'},
	{value: 'be', viewValue: 'BE', viewName: 'Belgium'},
	{value: 'bg', viewValue: 'BG', viewName: 'Bulgaria'},
	{value: 'hr', viewValue: 'HR', viewName: 'Croatia'},
	{value: 'cy', viewValue: 'CY', viewName: 'Cyprus'},
	{value: 'cz', viewValue: 'CZ', viewName: 'Czech Republic'},
	{value: 'dk', viewValue: 'DK', viewName: 'Denmark'},
	{value: 'ee', viewValue: 'EE', viewName: 'Estonia'},
	{value: 'fi', viewValue: 'FI', viewName: 'Finland'},
	{value: 'fr', viewValue: 'FR', viewName: 'France'},
	{value: 'gb', viewValue: 'GB', viewName: 'Great Britain'},
	{value: 'de', viewValue: 'DE', viewName: 'Germany'},
	{value: 'gr', viewValue: 'GR', viewName: 'Greece'},
	{value: 'hu', viewValue: 'HU', viewName: 'Hungary'},
	{value: 'ie', viewValue: 'IE', viewName: 'Ireland'},
	{value: 'it', viewValue: 'IT', viewName: 'Italy'},
	{value: 'lv', viewValue: 'LV', viewName: 'Latvia'},
	{value: 'lt', viewValue: 'LT', viewName: 'Lithuania'},
	{value: 'lu', viewValue: 'LU', viewName: 'Luxembourg'},
	{value: 'mt', viewValue: 'MT', viewName: 'Malta'},
	{value: 'nl', viewValue: 'NL', viewName: 'Netherlands'},
	{value: 'pl', viewValue: 'PL', viewName: 'Poland'},
	{value: 'pt', viewValue: 'PT', viewName: 'Portugal'},
	{value: 'ro', viewValue: 'RO', viewName: 'Romania'},
	{value: 'sk', viewValue: 'SK', viewName: 'Slovakia'},
	{value: 'si', viewValue: 'SI', viewName: 'Slovania'},
	{value: 'es', viewValue: 'ES', viewName: 'Spain'},
	{value: 'se', viewValue: 'SE', viewName: 'Sweden'},
	{value: 'ch', viewValue: 'CH', viewName: 'Switzerland'}
	];