export const PLACES = [
    {value: null, viewValue: ''},
    {value: 'abong-mbang', viewValue: 'ABONG-MBANG'},
    {value: 'akonolinga', viewValue: 'AKONOLINGA'},
    {value: 'bafang', viewValue: 'BAFANG'},
    {value: 'bafia', viewValue: 'BAFIA'},
    {value: 'baffia', viewValue: 'BAFFIA'},
    {value: 'bafoussam', viewValue: 'BAFOUSSAM'},
    {value: 'bafut', viewValue: 'BAFUT'},
    {value: 'bali', viewValue: 'BALI'},
    {value: 'bamenda', viewValue: 'BAMENDA'},
    {value: 'bandjoun', viewValue: 'BANDJOUN'},
    {value: 'bangangte', viewValue: 'BANGANGTE'},
    {value: 'banyo', viewValue: 'BANYO'},
    {value: 'batouri', viewValue: 'BATOURI'},
    {value: 'belabo', viewValue: 'BELABO'},
    {value: 'bertoua', viewValue: 'BERTOUA'},
    {value: 'blangoua', viewValue: 'BLANGOUA'},
    {value: 'bimbia', viewValue: 'BIMBIA'},
    {value: 'bogo', viewValue: 'BOGO'},
    {value: 'buea', viewValue: 'BUEA'},
    {value: 'dschang', viewValue: 'DSCHANG'},
    {value: 'douala', viewValue: 'DOUALA'},
    {value: 'ebolowa', viewValue: 'EBOLOWA'},
    {value: 'edea', viewValue: 'EDEA'},
    {value: 'ekona', viewValue: 'EKONA'},
    {value: 'ekondo-titi', viewValue: 'EKONDO-TITI'},
    {value: 'eseka', viewValue: 'ESEKA'},
    {value: 'eyumojok', viewValue: 'EYUMOJOK'},
    {value: 'figuil', viewValue: 'FIGUIL'},
    {value: 'fontem', viewValue: 'FONTEM'},
    {value: 'foumban', viewValue: 'FOUMBAN'},
    {value: 'foumbot', viewValue: 'FOUMBOT'},
    {value: 'garoua', viewValue: 'GAROUA'},
    {value: 'garoua-boulai', viewValue: 'GAROUA-BOULAI'},
    {value: 'guider', viewValue: 'GUIDER'},
    {value: 'guidiguis', viewValue: 'GUIDIGUIS'},
    {value: 'idenau', viewValue: 'IDENAU'},
    {value: 'kaele', viewValue: 'KAELE'},
    {value: 'kekem', viewValue: 'KEKEM'},
    {value: 'kousseri', viewValue: 'KOUSSERI'},
    {value: 'kumba', viewValue: 'KUMBA'},
    {value: 'kumbo', viewValue: 'KUMBO'},
    {value: 'kribi', viewValue: 'KRIBI'},
    {value: 'lagdo', viewValue: 'LAGDO'},
    {value: 'limbe', viewValue: 'LIMBE'},
    {value: 'loum', viewValue: 'LOUM'},
    {value: 'maga', viewValue: 'MAGA'},
    {value: 'magba', viewValue: 'MAGBA'},
    {value: 'malende', viewValue: 'MALENDE'},
    {value: 'mamfe', viewValue: 'MAMFE'},
    {value: 'manjo', viewValue: 'MANJO'},
    {value: 'maroua', viewValue: 'MAROUA'},
    {value: 'mbalmayo', viewValue: 'MBALMAYO'},
    {value: 'mbandjock', viewValue: 'MBANDJOCK'},
    {value: 'mbanga', viewValue: 'MBANGA'},
    {value: 'mbouda', viewValue: 'MBOUDA'},
    {value: 'meiganga', viewValue: 'MEIGANGA'},
    {value: 'melong', viewValue: 'MELONG'},
    {value: 'mokolo', viewValue: 'MOKOLO'},
    {value: 'mora', viewValue: 'MORA'},
    {value: 'muea', viewValue: 'MUEA'},
    {value: 'mundemba', viewValue: 'MUNDEMBA'},
    {value: 'mutengene', viewValue: 'MUTENGENE'},
    {value: 'muyuka', viewValue: 'MUYUKA'},
    {value: 'nanga-eboko', viewValue: 'NANGA-EBOKO'},
    {value: 'ndop', viewValue: 'NDOP'},
    {value: 'ngaoundal', viewValue: 'NGAOUNDAL'},
    {value: 'ngaoundere', viewValue: 'NGAOUNDERE'},
    {value: 'njombe', viewValue: 'NJOMBE'},
    {value: 'nkambe', viewValue: 'NKAMBE'},
    {value: 'nkongsamba', viewValue: 'NKONGSAMBA'},
    {value: 'nkoteng', viewValue: 'NKOTENG'},
    {value: 'obala', viewValue: 'OBALA'},
    {value: 'oku', viewValue: 'OKU'},
    {value: 'penja', viewValue: 'PENJA'},
    {value: 'pitoa', viewValue: 'PITOA'},
    {value: 'sangmelima', viewValue: 'SANGMELIMA'},
    {value: 'soa', viewValue: 'SOA'},
    {value: 'souza', viewValue: 'SOUZA'},
    {value: 'tcheboa', viewValue: 'TCHEBOA'},
    {value: 'tibati', viewValue: 'TIBATI'},
    {value: 'tiko', viewValue: 'TIKO'},
    {value: 'tombel', viewValue: 'TOMBEL'},
    {value: 'touboro', viewValue: 'TOUBORO'},
    {value: 'wum', viewValue: 'WUM'},
    {value: 'yagoua', viewValue: 'YAGOUA'},
    {value: 'yaounde', viewValue: 'YAOUNDE'},
    {value: 'yokadouma', viewValue: 'YOKADOUMA'}
];

export const DETAILS = [
   /* from/to, from/to, price, distance, road quality */
   {from: 'buea', to: 'bamenda', price: 6000, distance: 340, roadstate: 'AVERAGE'},
   {from: 'buea', to: 'bafoussam', price: 5000, distance: 270, roadstate: 'AVERAGE'},
   {from: 'buea', to: 'bimbia', price: 1200, distance: 39.5, roadstate: 'MIXED'},
   {from: 'buea', to: 'douala', price: 0, distance: 71.5, roadstate: 'GOOD'},
   {from: 'buea', to: 'ekona', price: 0, distance: 14.1, roadstate: 'GOOD'},
   {from: 'buea', to: 'eyumojok', price: 0, distance: 257, roadstate: 'N/A'},
   {from: 'buea', to: 'fontem', price: 0, distance: 249, roadstate: 'N/A'},
   {from: 'buea', to: 'idenau', price: 0, distance: 70.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'kribi', price: 0, distance: 271, roadstate: 'GOOD'},
   {from: 'buea', to: 'kumba', price: 0, distance: 71.4, roadstate: 'GOOD'},
   {from: 'buea', to: 'limbe', price: 1000, distance: 30.1, roadstate: 'GOOD'},
   {from: 'buea', to: 'mamfe', price: 10000, distance: 224, roadstate: 'BAD'},
   {from: 'buea', to: 'mundemba', price: 0, distance: 158, roadstate: 'N/A'},
   {from: 'buea', to: 'mutengene', price: 0, distance: 12.5, roadstate: 'GOOD'},
   {from: 'buea', to: 'muyuka', price: 1000, distance: 26.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'nkongsamba', price: 0, distance: 152, roadstate: 'MIXED'},
   {from: 'buea', to: 'tombel', price: 0, distance: 105, roadstate: 'N/A'},
   {from: 'buea', to: 'tiko', price: 500, distance: 17.8, roadstate: 'GOOD'},
   {from: 'buea', to: 'yaounde', price: 0, distance: 333, roadstate: 'AVERAGE'},

   {from: 'douala', to: 'bamenda', price: 6000, distance: 323, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'bafoussam', price: 5000, distance: 258, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'bertoua', price: 0, distance: 595, roadstate: 'N/A'},
   {from: 'douala', to: 'ebolowa', price: 0, distance: 319, roadstate: 'N/A'},
   {from: 'douala', to: 'edea', price: 0, distance: 92.7, roadstate: 'GOOD'},
   {from: 'douala', to: 'kumba', price: 2500, distance: 136, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'limbe', price: 2000, distance: 77.3, roadstate: 'GOOD'},
   {from: 'douala', to: 'kribi', price: 0, distance: 250, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'mamfe', price: 12000, distance: 288, roadstate: 'MIXED'},
   {from: 'douala', to: 'nkongsamba', price: 0, distance: 149, roadstate: 'GOOD'},
   {from: 'douala', to: 'tibati', price: 0, distance: 680, roadstate: 'MIXED'},
   {from: 'douala', to: 'tiko', price: 0, distance: 55.5, roadstate: 'GOOD'},
   {from: 'douala', to: 'yaounde', price: 3500, distance: 263, roadstate: 'GOOD'},

   {from: 'limbe', to: 'bimbia', price: 0, distance: 11.6, roadstate: 'BAD'},
   {from: 'limbe', to: 'ekona', price: 0, distance: 36.7, roadstate: 'GOOD'},
   {from: 'limbe', to: 'ejumojok', price: 0, distance: 280, roadstate: 'MIXED'},
   {from: 'limbe', to: 'idenau', price: 0, distance: 42.3, roadstate: 'GOOD'},
   {from: 'limbe', to: 'kumba', price: 0, distance: 94.1, roadstate: 'GOOD'},
   {from: 'limbe', to: 'mamfe', price: 0, distance: 246, roadstate: 'GOOD'},
   {from: 'limbe', to: 'mutengene', price: 0, distance: 17.5, roadstate: 'GOOD'},
   {from: 'limbe', to: 'tiko', price: 0, distance: 23.3, roadstate: 'GOOD'},

   {from: 'muyuka', to: 'baffia', price: 0, distance: 17.8, roadstate: 'BAD'},
   {from: 'muyuka', to: 'bafoussam', price: 4200, distance: 240, roadstate: 'BAD'},
   {from: 'muyuka', to: 'bamenda', price: 5000, distance: 317.0, roadstate: 'AVERAGE'},
   {from: 'muyuka', to: 'douala', price: 2000, distance: 90.1, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'ekona', price: 0, distance: 12.4, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'idenau', price: 0, distance: 89.0, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'kumba', price: 0, distance: 45.5, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'limbe', price: 0, distance: 49.0, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'malende', price: 0, distance: 6.6, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'mamfe', price: 0, distance: 198, roadstate: 'N/A'},
   {from: 'muyuka', to: 'mundemba', price: 0, distance: 134, roadstate: 'N/A'},
   {from: 'muyuka', to: 'mutengene', price: 0, distance: 31.4, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'tiko', price: 0, distance: 36.7, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'tombel', price: 0, distance: 78.2, roadstate: 'N/A'},
   {from: 'muyuka', to: 'yaounde', price: 0, distance: 352.0, roadstate: 'AVERAGE'},

   {from: 'tiko', to: 'douala', price: 0, distance: 55.4, roadstate: 'GOOD'}
];

export const CURRENCIES = [
    {value: null, viewValue: ''},
    {value: 'cad', viewValue: 'CAD'},
    {value: 'cny', viewValue: 'CNY'},
    {value: 'gbp', viewValue: 'GBP'},
    {value: 'eur', viewValue: 'EUR'},
    {value: 'kes', viewValue: 'KES'},
    {value: 'ngn', viewValue: 'NGN'},
    {value: 'usd', viewValue: 'USD'},
    {value: 'zar', viewValue: 'ZAR'},
];