
export const START = [
    {value: null, viewValue: ''},
    {value: 'baffia', viewValue: 'BAFFIA'},
    {value: 'bafoussam', viewValue: 'BAFOUSSAM'},
    {value: 'bamenda', viewValue: 'BAMENDA'},
    {value: 'bimbia', viewValue: 'BIMBIA'},
    {value: 'buea', viewValue: 'BUEA'},
    {value: 'douala', viewValue: 'DOUALA'},
    {value: 'edea', viewValue: 'EDEA'},
    {value: 'ekona', viewValue: 'EKONA'},
    {value: 'eyumojok', viewValue: 'EYUMOJOK'},
    {value: 'fontem', viewValue: 'FONTEM'},
    {value: 'idenau', viewValue: 'IDENAU'},
    {value: 'kumba', viewValue: 'KUMBA'},
    {value: 'kribi', viewValue: 'KRIBI'},
    {value: 'limbe', viewValue: 'LIMBE'},
    {value: 'malende', viewValue: 'MALENDE'},
    {value: 'mamfe', viewValue: 'MAMFE'},
    {value: 'mundemba', viewValue: 'MUNDEMBA'},
    {value: 'mutengene', viewValue: 'MUTENGENE'},
    {value: 'muyuka', viewValue: 'MUYUKA'},
    {value: 'tibati', viewValue: 'TIBATI'},
    {value: 'tiko', viewValue: 'TIKO'},
    {value: 'tombel', viewValue: 'TOMBEL'},
    {value: 'yaounde', viewValue: 'YAOUNDE'}
];

export const END = [
    {value: null, viewValue: ''},
    {value: 'baffia', viewValue: 'BAFFIA'},
    {value: 'bafoussam', viewValue: 'BAFOUSSAM'},
    {value: 'bamenda', viewValue: 'BAMENDA'},
    {value: 'bimbia', viewValue: 'BIMBIA'},
    {value: 'buea', viewValue: 'BUEA'},
    {value: 'douala', viewValue: 'DOUALA'},
    {value: 'edea', viewValue: 'EDEA'},
    {value: 'ekona', viewValue: 'EKONA'},
    {value: 'eyumojok', viewValue: 'EYUMOJOK'},
    {value: 'fontem', viewValue: 'FONTEM'},
    {value: 'idenau', viewValue: 'IDENAU'},
    {value: 'kumba', viewValue: 'KUMBA'},
    {value: 'kribi', viewValue: 'KRIBI'},
    {value: 'limbe', viewValue: 'LIMBE'},
    {value: 'malende', viewValue: 'MALENDE'},
    {value: 'mamfe', viewValue: 'MAMFE'},
    {value: 'mundemba', viewValue: 'MUNDEMBA'},
    {value: 'mutengene', viewValue: 'MUTENGENE'},
    {value: 'muyuka', viewValue: 'MUYUKA'},
    {value: 'tibati', viewValue: 'TIBATI'},
    {value: 'tiko', viewValue: 'TIKO'},
    {value: 'tombel', viewValue: 'TOMBEL'},
    {value: 'yaounde', viewValue: 'YAOUNDE'}
];

export const DETAILS = [
   /* from/to, from/to, price, distance, road quality */
   {from: 'buea', to: 'bamenda', price: 6000, distance: 340, roadstate: 'AVERAGE'},
   {from: 'buea', to: 'bafoussam', price: 0, distance: 270, roadstate: 'AVERAGE'},
   {from: 'buea', to: 'douala', price: 0, distance: 71.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'ejumojok', price: 0, distance: 257, roadstate: 'GOOD'},
   {from: 'buea', to: 'idenau', price: 0, distance: 70.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'kribi', price: 0, distance: 271, roadstate: 'GOOD'},
   {from: 'buea', to: 'kumba', price: 0, distance: 71.4, roadstate: 'GOOD'},
   {from: 'buea', to: 'limbe', price: 0, distance: 30.1, roadstate: 'GOOD'},
   {from: 'buea', to: 'mamfe', price: 0, distance: 224, roadstate: 'BAD'},
   {from: 'buea', to: 'mutengene', price: 0, distance: 12.5, roadstate: 'GOOD'},
   {from: 'buea', to: 'muyuka', price: 1000, distance: 26.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'tiko', price: 0, distance: 17.8, roadstate: 'GOOD'},
   {from: 'buea', to: 'yaounde', price: 0, distance: 333, roadstate: 'AVERAGE'},

   {from: 'douala', to: 'bamenda', price: 0, distance: 323, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'bafoussam', price: 0, distance: 258, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'bertoua', price: 0, distance: 595, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'ebolowa', price: 0, distance: 319, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'edea', price: 0, distance: 92.7, roadstate: 'GOOD'},
   {from: 'douala', to: 'kumba', price: 2500, distance: 136, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'limbe', price: 0, distance: 77.3, roadstate: 'GOOD'},
   {from: 'douala', to: 'kribi', price: 0, distance: 250, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'tiko', price: 0, distance: 55.5, roadstate: 'GOOD'},
   {from: 'douala', to: 'yaounde', price: 0, distance: 263, roadstate: 'GOOD'},

   {from: 'limbe', to: 'bimbia', price: 0, distance: 11.6, roadstate: 'BAD'},
   {from: 'limbe', to: 'ekona', price: 0, distance: 36.7, roadstate: 'GOOD'},
   {from: 'limbe', to: 'ejumojok', price: 0, distance: 280, roadstate: 'MIXED'},
   {from: 'limbe', to: 'idenau', price: 0, distance: 42.3, roadstate: 'GOOD'},
   {from: 'limbe', to: 'kumba', price: 0, distance: 94.1, roadstate: 'GOOD'},
   {from: 'limbe', to: 'mamfe', price: 0, distance: 246, roadstate: 'GOOD'},
   {from: 'limbe', to: 'mutengene', price: 0, distance: 17.5, roadstate: 'GOOD'},
   {from: 'limbe', to: 'tiko', price: 0, distance: 23.3, roadstate: 'GOOD'},

   {from: 'muyuka', to: 'baffia', price: 0, distance: 17.8, roadstate: 'BAD'},
   {from: 'muyuka', to: 'bamenda', price: 0, distance: 317.0, roadstate: 'AVERAGE'},
   {from: 'muyuka', to: 'douala', price: 0, distance: 90.1, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'ekona', price: 0, distance: 12.4, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'idenau', price: 0, distance: 89.0, roadstate: 'N/A'},
   {from: 'muyuka', to: 'kumba', price: 0, distance: 45.5, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'limbe', price: 0, distance: 49.0, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'malende', price: 0, distance: 6.6, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'mamfe', price: 0, distance: 198, roadstate: 'N/A'},
   {from: 'muyuka', to: 'mutengene', price: 0, distance: 31.4, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'tiko', price: 0, distance: 36.7, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'tombel', price: 0, distance: 78.2, roadstate: 'N/A'},
   {from: 'muyuka', to: 'yaounde', price: 0, distance: 352.0, roadstate: 'AVERAGE'},

   {from: 'tiko', to: 'douala', price: 0, distance: 55.4, roadstate: 'GOOD'}
];