
export const START = [
    {value: null, viewValue: ''},
    {value: 'bamenda', viewValue: 'BAMENDA'},
    {value: 'buea', viewValue: 'BUEA'},
    {value: 'douala', viewValue: 'DOUALA'},
    {value: 'kumba', viewValue: 'KUMBA'},
    {value: 'limbe', viewValue: 'LIMBE'},
    {value: 'mamfe', viewValue: 'MAMFE'},
    {value: 'mutengene', viewValue: 'MUTENGENE'},
    {value: 'muyuka', viewValue: 'MUYUKA'},
    {value: 'tombel', viewValue: 'TOMBEL'},
    {value: 'tibati', viewValue: 'TIBATI'},
    {value: 'tiko', viewValue: 'TIKO'},
    {value: 'yaounde', viewValue: 'YAOUNDE'}
];

export const END = [
    {value: null, viewValue: ''},
    {value: 'baffia', viewValue: 'BAFFIA'},
    {value: 'bafoussam', viewValue: 'BAFOUSSAM'},
    {value: 'bamenda', viewValue: 'BAMENDA'},
    {value: 'buea', viewValue: 'BUEA'},
    {value: 'douala', viewValue: 'DOUALA'},
    {value: 'ekona', viewValue: 'EKONA'},
    {value: 'eyumojok', viewValue: 'EYUMOJOK'},
    {value: 'fontem', viewValue: 'FONTEM'},
    {value: 'idenau', viewValue: 'IDENAU'},
    {value: 'kumba', viewValue: 'KUMBA'},
    {value: 'limbe', viewValue: 'LIMBE'},
    {value: 'mamfe', viewValue: 'MAMFE'},
    {value: 'mundemba', viewValue: 'MUNDEMBA'},
    {value: 'mutengene', viewValue: 'MUTENGENE'},
    {value: 'muyuka', viewValue: 'MUYUKA'},
    {value: 'tibati', viewValue: 'TIBATI'},
    {value: 'tiko', viewValue: 'TIKO'},
    {value: 'tombel', viewValue: 'TOMBEL'},
    {value: 'yaounde', viewValue: 'YAOUNDE'}
];

export const DETAILS = [
   /* from/to, from/to, price, distance, road state */
   {from: 'buea', to: 'bamenda', price: 4600, distance: 336, roadstate: 'AVERAGE'},
   {from: 'buea', to: 'bafoussam', price: 3900, distance: 280, roadstate: 'AVERAGE'},
   {from: 'buea', to: 'douala', price: 1200, distance: 71.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'idenau', price: 2000, distance: 70.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'kribi', price: 2900, distance: 271, roadstate: 'GOOD'},
   {from: 'buea', to: 'kumba', price: 1300, distance: 71.4, roadstate: 'GOOD'},
   {from: 'buea', to: 'limbe', price: 500, distance: 30.1, roadstate: 'GOOD'},
   {from: 'buea', to: 'mamfe', price: 3300, distance: 224, roadstate: 'BAD'},
   {from: 'buea', to: 'mutengene', price: 150, distance: 12.5, roadstate: 'GOOD'},
   {from: 'buea', to: 'muyuka', price: 400, distance: 26.2, roadstate: 'GOOD'},
   {from: 'buea', to: 'tiko', price: 300, distance: 17.8, roadstate: 'GOOD'},
   {from: 'buea', to: 'yaounde', price: 3500, distance: 371, roadstate: 'AVERAGE'},
   {from: 'douala', to: 'kribi', price: 1900, distance: 250, roadstate: 'AVERAGE'},
   {from: 'tiko', to: 'douala', price: 700, distance: 55.4, roadstate: 'GOOD'},

   {from: 'muyuka', to: 'baffia', price: 250, distance: 17.8, roadstate: 'BAD'},
   {from: 'muyuka', to: 'bamenda', price: 3200, distance: 317.0, roadstate: 'AVERAGE'},
   {from: 'muyuka', to: 'douala', price: 1200, distance: 90.1, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'ekona', price: 300, distance: 12.4, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'idenau', price: 2000, distance: 89.0, roadstate: 'N/A'},
   {from: 'muyuka', to: 'kumba', price: 800, distance: 45.5, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'limbe', price: 1000, distance: 49.0, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'malende', price: 150, distance: 6.6, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'mutengene', price: 800, distance: 31.4, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'tiko', price: 900, distance: 36.7, roadstate: 'GOOD'},
   {from: 'muyuka', to: 'tombel', price: 0, distance: 78.2, roadstate: 'N/A'},
   {from: 'muyuka', to: 'yaounde', price: 4500, distance: 352.0, roadstate: 'AVERAGE'}
];

/*
SW Region
mundemba,
kendem,
ekondo titi,
mbonge,
tombel,
manyemen,
nguti,
eyang,
tinto,
kembong,
fontem,
etuku,
small ekombe,
new barombi,
malende,
ekona,
mondoni,
moliwe,
bonadikombo,
batoke,
bakingili,
idenau,
eyumojok,
numba,
dikome,
besongabang,
bolifamba,
moliwe,
mondoni,
malende,
ekombe bonji,
small ekombe,
kombone,
bekondo,
mofako bekondo
*/