export const CURRENCIES = [
    {value: null, viewValue: ''},
    {value: 'aed', viewValue: 'AED'},
    {value: 'cad', viewValue: 'CAD'},
    {value: 'cny', viewValue: 'CNY'},
    {value: 'eur', viewValue: 'EUR'},
    {value: 'gbp', viewValue: 'GBP'},
    {value: 'ghs', viewValue: 'GHS'},
    {value: 'inr', viewValue: 'INR'},
    {value: 'kes', viewValue: 'KES'},
    {value: 'ngn', viewValue: 'NGN'},
    {value: 'usd', viewValue: 'USD'},
    {value: 'xof', viewValue: 'XOF'},
    {value: 'zar', viewValue: 'ZAR'},
];